mido: patched blobs to resolve issue with newer PhoneStateListener method
* It helps if you expirience following crash:

 E AndroidRuntime: FATAL EXCEPTION: MainEventThread
 E AndroidRuntime: Process: .dataservices, PID: 24689
 E AndroidRuntime: java.lang.NoSuchMethodError: No direct method <init>(ILandroid/os/Looper;)V in class Landroid/telephony/PhoneStateListener; or its super classes (declaration of 'android.telephony.PhoneStateListener' appears in /system/framework/framework.jar:classes2.dex)
 E AndroidRuntime:        at com.quicinc.cne.CNE$8.<init>(CNE.java:2475)
 E AndroidRuntime:        at com.quicinc.cne.CNE.registerPhoneStateListener(CNE.java:2475)
 E AndroidRuntime:        at com.quicinc.cne.CNE.-wrap5(Unknown Source:0)
 E AndroidRuntime:        at com.quicinc.cne.CNE$6.handleMessage(CNE.java:1681)
 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:105)
 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:164)
 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:65)
 I Process : Sending signal. PID: 24689 SIG: 9

* com.quicinc.cne.jar and CNEService.apk was decompiled by apktol and edited
to match newer method:

 decompile both files like:
 java -jar ../apktool.jar d CNEService.apk

 edit smali with PhoneStateListener;-><init> call to look like this
.method constructor <init>(Lcom/quicinc/cne/CNE;ILandroid/os/Looper;)V
    .locals 1
    .param p1, "this$0"    # Lcom/quicinc/cne/CNE;
    .param p2, "$anonymous0"    # I
    .param p3, "$anonymous1"    # Landroid/os/Looper;
    .prologue
    .line 2475
    iput-object p1, p0, Lcom/quicinc/cne/CNE$8;->this$0:Lcom/quicinc/cne/CNE;
    new-instance v0, Ljava/lang/Integer;
    invoke-direct {v0, p2}, Ljava/lang/Integer;-><init>(I)V
    invoke-direct {p0, v0, p3}, Landroid/telephony/PhoneStateListener;-><init>(Ljava/lang/Integer;Landroid/os/Looper;)V
    return-void
.end method

 It adding converter fron Int to Integer class

 build files back:
 java -jar ../apktool.jar b -c  CNEService

 apk requires LOCAL_CERTIFICATE:= PRESIGNED  or ends with this:

 E AndroidRuntime: java.lang.VerifyError: Verifier rejected class com.quicinc.cne.CNE$8: void com.quicinc.cne.CNE$8.<init>(com.quicinc.cne.CNE, int, android.os.Looper) failed to verify: void com.quicinc.cne.CNE$8.<init>(com.quicinc.cne.CNE, int, android.os.Looper): [0x7] Expected initialization on uninitialized reference Precise Reference: java.lang.Integer (declaration of 'com.quicinc.cne.CNE$8' appears in /system/framework/com.quicinc.cne.jar)
 E AndroidRuntime: 	at com.quicinc.cne.CNE.registerPhoneStateListener(CNE.java:2475)
 E AndroidRuntime: 	at com.quicinc.cne.CNE.-wrap5(Unknown Source:0)
 E AndroidRuntime: 	at com.quicinc.cne.CNE$6.handleMessage(CNE.java:1681)
 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
 E AndroidRuntime: 	at android.os.HandlerThread.run(HandlerThread.java:65)